Bug data
aceleradora-TW/nossa-casa-front pull request #154
Opened 2024-02-06 13:07 UTC by angeloneves19

# 148  Bug: Data 

### 🆙 CHANGELOG

- Adicionamos a string GMT dentro do New Date( )  no carrossel de eventos, na descrição de eventos, oficinas e terapias.

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Acessar a branch  bug_data.
- [ ] Rodar o projeto no CMS e Front-end.
- [ ] Verificar se as datas adicionadas no Strapi, condizem com as datas dos eventos, oficinas e terapias.
- [ ] Fazer deploy em ambiente de teste
- [ ] Abrir URL da aplicação de teste
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2024-02-06 16:22 UTC, daniellemadrid approved these changes

2024-02-07 13:13 UTC, yrachid commented on src/components/events-carrosel/index.js
> +                        <p className="date">{events.date.toLocaleDateString('pt-BR', { Timezone: 'UTC' })}</p>
```suggestion
                        <p className="date">{events.date.toLocaleDateString('pt-BR', { timeZone: 'UTC' })}</p>
```

2024-02-07 13:15 UTC, yrachid commented on src/components/events-carrosel/index.js
> +            date: new Date(`${data.attributes.data_inicio}T00:00:00-0300`),
Porque estamos adicionando horário e offset de timezone? Qual é o bug que ocorre quando esta informação não está presente?

O que acontecerá quando o Brasil entrar em horário de verão e o offset mudar para `-0200`?

2024-02-07 13:17 UTC, yrachid commented on src/helpers/format-data/index.js
> +      : `${formatDate(new Date(`${workshop.attributes?.data_inicio}T00:00:00-0300`))}
Essa correção está se repetindo em tudo que é canto. Não seria melhor deixar a função `formatDate` fazer isso internamente? Continuamos passando a string de data para ela e ela concatena a informação faltante, assim não precisamos repetir a mesma coisa toda vez que a função for chamada.

2024-02-07 13:25 UTC, yrachid requested changes

2024-02-07 13:25 UTC, yrachid commented on src/components/events-carrosel/index.js
> +            date: new Date(`${data.attributes.data_inicio}T00:00:00-0300`),
Preciso entender melhor o problema que está ocorrendo, mas tenho a impressão de que concatenar um offset de timezone não será a solução.

Acho que deveríamos continuar lidando com datas em UTC e só mudarmos o offset na hora de exibir o valor da data. Já fazemos isso no código desse componente, só estamos fazendo errado hehehe:

Mais para baixo, fazemos:

```javascript
events.date.toLocaleDateString('pt-BR', { Timezone: 'UTC' }
```

Quando poderíamos fazer:

```
events.date.toLocaleDateString('pt-BR', { timeZone: 'America/Sao_Paulo' }
```

Isso vai ajustar a data para o horário de Brasília e já vai dar conta de converter corretamente horário de verão. Já havia falado sobre isso em uma PR bem antiga.

2024-02-12 13:54 UTC, closed without merging