06/feat home galerias
aceleradora-TW/nossa-casa-front pull request #19
Opened 2023-05-30 17:47 UTC by nicofercavv-dev

#6  - Home Galerias
====
  
### 🆙 CHANGELOG

- Mudar as cores da sessão galeria
- Criar modal ver mais fotos
- Criar carrossel de imagens
- Criar carrossel de slides

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Startar o projeto na branch 06/feat-home-galerias
- [ ] Abrir URL da aplicação de teste
- [ ] Verificar se as cores da sessão galeria foram mudadas
- [ ] Verificar se a modal está funcionando
- [ ] Verificar se existe um carrossel e se está funcionando
- [ ] Verificar se o carrossel de slides abaixo está funcionando
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2023-05-30 20:09 UTC, FernandoMNascimento commented on src/components/carousel/index.js
> +  const verifyIfLastSlide = () => {
"verificar se é o ultimo slide"não é o objetivo desse método. Esse método vai pro proximo slide à direita, ou votla pro começo. Talvez um nome melhor pra ele seja `goToNextSlide`

2023-05-30 20:35 UTC, FernandoMNascimento commented on src/components/carousel/index.js
> +      {photos.map((photo, index) => <img key={photo} src={photo} className={index === currentSlide ? 'active' : ''} style={{ transform: `translateX(${currentSlide + 1 > slidesLimit ? -125 : 0}%)` }}
sugestão:
```index === currentSlide ? 'active' : ''```
Pode ter um método unico pra isso. Algo como `getSlideClassName`

2023-05-30 20:38 UTC, FernandoMNascimento commented on src/components/galery-modal/index.js
> +  const [photos, setPhotos] = useState([teste, teste2, teste3, teste, teste2, teste3, teste, teste2])
recomendo usar nomes mais significativos ao invés de `teste`. Por exemplo, `defaultGrafittiPanelImage`. Isso vale para as 3 imagens

2023-05-30 20:41 UTC, FernandoMNascimento commented on src/pages/home/styled.js
> +        font-size: 50px;
Existe algum motivo pra trocar o tamanho de rem pra px? geralmente, em ou rem são mais utilizados em layouts responsíveis.

2023-05-30 20:50 UTC, FernandoMNascimento commented on src/components/carousel/index.js
> +  const slidesLimit = 7
`slidesLimit` só é utilizado em um momento (linha 43) e, na prática, poderia ser utilizado  `photos.length - 1`. 
Talvez seja melhor fazer a verificação do tamanho do array de entrada no componente "pai" de `CarouselGallery`.
Resumindo: remover `slidesLimit`

2023-05-31 00:07 UTC, daniellemadrid requested changes

2023-05-31 00:07 UTC, daniellemadrid commented on src/components/galery-modal/index.js
> +    <button onClick={() => setToggleGalery(!toggleGalery)}>Ver mais</button>
Este onClick realiza a mesma ação que a linha 21, poderíamos transformar em uma função handle reutilizável, ex:

```
const toggleGaleryHandler ( ) => {
//o código aqui
}
```

Após isso, só chamar a mesma no onClick, ex.:

```
<button onClick={toggleGaleryHandler}>Ver mais</button>
```

note que: ao utilizar uma função que não recebe parametro, podemos apenas chamar o seu nome dentro de um onClick, ou seja, vamos de: 

```
onClick={() => toggleGaleryHandler()}
 ```

para apenas 

```
onClick={toggleGaleryHandler}
```

2023-06-01 14:47 UTC, FernandoMNascimento approved these changes

2023-06-01 14:47 UTC, FernandoMNascimento commented on src/components/galery-modal/index.js
> +    <button onClick={() => toggleGaleryHandler()}>Ver mais</button>
Vocês podem susbstituir `onClick={() => toggleGaleryHandler()}` por `onClick={toggleGaleryHandler}`

2023-06-01 14:47 UTC, FernandoMNascimento commented on src/components/galery-modal/index.js
> +        <img className='exit' src={closeIcon} onClick={() => toggleGaleryHandler()}/>
Msm coisa acima, 
vocês podem susbstituir `onClick={() => toggleGaleryHandler()}` por `onClick={toggleGaleryHandler}`

2023-06-01 16:41 UTC, merged