feat(src/home && src/components): criação da seção e modal sobre - @k…
aceleradora-TW/nossa-casa-front pull request #23
Opened 2023-06-05 14:12 UTC by cintia89

…-js @cintia89

#<5> - Feat: Home: componente sobre
====
  
### 🆙 CHANGELOG

*Esses passos são apenas exemplos*

- inserir uma foto na sessão sobre ao lado de uma breve descrição na pagina home
- refatorar o componente modalGalery para ser reutilizado na modal da sessão sobre
- dentro da modal inserir titulo, subtitulos e paragrafos sobre a historia da nossa casa

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] entrar na brant: 5-home-modal-sobre
- [ ] Rodar comando yarn start no terminal
- [ ] Verificar foto da sessão sobre na pagina home
- [ ] verificar se o botão saiba mais esta clicavel e se abre modal
- [ ] verificar se modal fecha 
- [ ] verificar se dentro da modal consta titulo, subtitulos e paragrafos sobre a historia da nossa casa
- [ ] Comparar a barra de navegação com a do protótipo do [Figma](https://www.figma.com/file/m4ejKAkgRMcNSzhiMLcoFp/Aceleradora-%C3%81gil-%E2%80%93%C2%A0Prot%C3%B3tipo-de-alta-fidelidade-%7C-Nossa-Casa?type=design&node-id=148%3A56547&t=yqUrNg8rkwRzjHG4-1)
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2023-06-05 14:20 UTC, daniellemadrid approved these changes

2023-06-05 14:39 UTC, FernandoMNascimento requested changes

2023-06-05 14:39 UTC, FernandoMNascimento commented on src/components/galery-modal/index.js
> +  const buttonTextByTypes = {
essa constante pode ser posta num arquivo `.constants.js` à parte, e importada neste componente

2023-06-05 17:18 UTC, narukaioh approved these changes

2023-06-06 16:27 UTC, FernandoMNascimento approved these changes

2023-07-03 18:53 UTC, merged