14/eventos carrosel
aceleradora-TW/nossa-casa-front pull request #61
Opened 2023-08-14 18:16 UTC by PabloHunter

#<NUMERO-DO-CARD> - Titulo do Card
====
  
### 🆙 CHANGELOG

- Verificar se ha um carrossel dos eventos disponíveis conforme protótipo no https://www.figma.com/file/m4ejKAkgRMcNSzhiMLcoFp/Aceleradora-Ágil-–%C2%A0Protótipo-de-alta-fidelidade-%7C-Nossa-Casa?type=design&node-id=1149-9755&mode=design&t=rPZkpbicSq9WbkZh-4
- Carrossel deve mostrar foto, nome do eventos, data  e botão ver mais 
- Botão ver mais deve abrir uma modal 
- Ordenamento dos eventos  por data mais proxima 

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Acessar a branch 14
- [ ] Ir na pagina de eventos 
- [ ] Verificar se no carrossel aparece foto, titulo do evento, data e botão Ver Mais
- [ ] Verificar se botão ver mais leva para a modal de detalhes da oficina
- [ ] Verificar se ordenamento das oficinas por data
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2023-08-14 18:53 UTC, daniellemadrid requested changes
nomes, prevenção de get desnecessário e deixar de usar string como validação

2023-08-14 18:53 UTC, daniellemadrid commented on src/components/events-carrosel/index.js
> +    cms.get('api/events/?populate=foto_divulgacao').then((response) => {
é valido termos uma verificação aqui para não realizar o get quando não houver necessidade, para isso é só adicionar a linha `if (attributes) return` ao inicio do useEffect. Isso irá previnir requests desnecessárias

2023-08-14 18:53 UTC, daniellemadrid commented on src/components/events-modal/index.js
> +  const [modal, setModal] = useState(false)
isso poderia se chamar showModal e setShowModal

2023-08-14 18:53 UTC, daniellemadrid commented on src/components/events-modal/index.js
> +    setModal(modal => !modal)
aqui poderia ser realizado apenas a inversão do valor diretamente, `setModal(!modal)`

2023-08-14 18:53 UTC, daniellemadrid commented on src/components/navbar/index.js
>      setToggle(toggle === 'aparece' ? '' : 'aparece')
acredito que não pertença as suas alterações, mas, poderiamos mudar isso para boolean e deixarmos de utilizar a string "aparece" como validação.

Sugiro que o useState seja `const [toggle, setToggle] = useState(false)` e que a função apenas inverta esse valor

`const onClickMenu = () => { setToggle(!toggle) }`

2023-08-14 18:53 UTC, daniellemadrid commented on src/components/navbar/index.js
> +      <div className={`redirecionamento ${toggle}`}>
após mudar o useState, utilizar um if ternário para decidir se iremos definir como "aparece" ou não, da seguinte forma: `<div className={redirecionamento ${toggle ? "aparece" : ""}}>`

2023-08-15 18:01 UTC, JCdantss commented on src/components/events-carrosel/index.js
> +    cms.get('api/events/?populate=foto_divulgacao').then((response) => {
consegui fazer a mudanca do if

2023-08-15 18:02 UTC, JCdantss commented on src/components/events-modal/index.js
> +    setModal(modal => !modal)
tentei fazer essa refatoracao so que nao da pra ficar ele nao reconhece
o !modal

2023-08-15 18:02 UTC, JCdantss commented on src/components/navbar/index.js
>      setToggle(toggle === 'aparece' ? '' : 'aparece')
eu acho que esse tem que fazer em outra branch nao e?

2023-08-15 18:03 UTC, JCdantss commented on src/components/navbar/index.js
> +      <div className={`redirecionamento ${toggle}`}>
aqui tbm em outra branch?

2023-08-16 12:08 UTC, daniellemadrid commented on src/components/navbar/index.js
>      setToggle(toggle === 'aparece' ? '' : 'aparece')
não seria necessário

2023-08-16 12:08 UTC, daniellemadrid commented on src/components/navbar/index.js
> +      <div className={`redirecionamento ${toggle}`}>
não seria necessário

2023-08-16 15:03 UTC, PabloHunter commented on src/components/navbar/index.js
>      setToggle(toggle === 'aparece' ? '' : 'aparece')
concluido

2023-08-16 15:04 UTC, PabloHunter commented on src/components/events-modal/index.js
> +    setModal(modal => !modal)
resolvido

2023-08-16 17:19 UTC, PabloHunter commented on src/components/events-modal/index.js
> +    setModal(modal => !modal)
resolvido

2023-08-16 18:31 UTC, PabloHunter commented on src/components/navbar/index.js
> +      <div className={`redirecionamento ${toggle}`}>
resolvido

2023-08-17 13:45 UTC, daniellemadrid approved these changes

2023-08-17 14:27 UTC, merged